sudo: false
language: scala
jdk:
- oraclejdk8
scala:
- 2.12.6

before_cache:
# Cleanup the cached directories to avoid unnecessary cache updates
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -delete
- find $HOME/.sbt        -name "*.lock"               -delete

cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt